arch:
- arm64

language: generic

env:
- IMGNAME=ahmedbendo/ubuntu:dbot
- INSTALL_LOCATION=/home/ubuntu

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host ${IPADDR}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key ${user}@${IPADDR} pwd
- docker image build -t ${IMGNAME} .

script:
- dig +short myip.opendns.com @resolver1.opendns.com


after_success:
- ssh -i ./deploy_key ${user}@${IPADDR} ls -lha /home/ubuntu/.ssh
- ssh -i ./deploy_key ${user}@${IPADDR} "cd ${INSTALL_LOCATION} && git pull ${TRAVIS_BUILD_WEB_URL} && docker image build -t ${IMGNAME} ${INSTALL_LOCATION}/. &&  docker stop discordbot; docker rm discordbot; docker run --name discordbot --restart always -d  ${IMGNAME}"

